### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by sehHeiden** [BuntingLabs/mundipy#2]
Path: /loading-datasets.mdx

Which Data types are supported? Everything Fiona can open?

**Comment by brendanashworth** [comment]
Right — we should probably create a dropdown with a full list of supported file types here.

It can open everything Fiona can open, in addition to PostGIS tables. I'll fix this table.

**Comment by brendanashworth** [comment]
This is fixed in the latest docs: https://docs.mundi.ai/manual/datasets

Thanks
